default: &default
  adapter: mysql2
  encoding: utf8
  database: vue_sample_app
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  user_name: root
  database: vue_sample_app
  host: localhost
  password:

test:
  <<: *default

production:
  <<: *default
